/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.kototuz.proxy_app;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_tile_default=0x7f020000;
    }
    public static final class id {
        public static final int proxy_list=0x7f040000;
    }
    public static final class layout {
        public static final int proxy_item=0x7f030000;
        public static final int simple_layout=0x7f030001;
    }
}
